version: '3.7'
services:

  # docker-compose exec web /bin/bash

  web:
    build:
      context: ./web
    depends_on:
      - mysql
    ports:
      - 5080:80
    volumes:
      - type: bind
        # source: ./
        # target: /root/host
        source: ./web/portal
        target: /root/home/portal
      - type: bind
        source: ./web
        target: /root/host

        
  mysql:
    image: mariadb/server
    environment:
      - MARIADB_ROOT_PASSWORD=mypassword
      - MARIADB_DATABASE=testing_db
      - MARIADB_USER=bruno
      - MARIADB_PASSWORD=password

  # mysql -u root -pmypassword -h mysql testing_db
  # mysql -u bruno -ppassword -h mysql testing_db < create_table_numbers.sql